# Generated by Django 5.2.5 on 2025-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_created_by_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
