# Generated by Django 5.2.5 on 2025-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_entry_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
