# Generated by Django 5.2.5 on 2025-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_entry_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
