# Generated by Django 5.2.5 on 2025-09-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='joined_on',
            new_name='created_at',
        ),
    ]
