# Generated by Django 5.2.5 on 2025-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event_time_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pass_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
